<?$APPLICATION->IncludeComponent("bitrix:catalog.viewed.products", "",
	Array(
		"SHOW_FROM_SECTION" => "N",
		"HIDE_NOT_AVAILABLE" => "N",
		"SHOW_DISCOUNT_PERCENT" => "N",
		"PRODUCT_SUBSCRIPTION" => "N",
		"SHOW_NAME" => "Y",
		"SHOW_IMAGE" => "Y",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"PAGE_ELEMENT_COUNT" => "15",
		"LINE_ELEMENT_COUNT" => "15",
		"TEMPLATE_THEME" => "",
		"DETAIL_URL" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "86400",
		"CACHE_GROUPS" => "Y",
		"SHOW_OLD_PRICE" => "N",
		"PRICE_CODE" => array(),
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"CONVERT_CURRENCY" => "N",
		"BASKET_URL" => "/personal/cart/",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"ADD_PROPERTIES_TO_BASKET" => "N",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"SHOW_PRODUCTS_#ITEMS_IBLOCK_ID#" => "Y",
		"PROPERTY_CODE_#ITEMS_IBLOCK_ID#" => array(),
		"CART_PROPERTIES_#ITEMS_IBLOCK_ID#" => array(),
		"ADDITIONAL_PICT_PROP_#ITEMS_IBLOCK_ID#" => "",
		"LABEL_PROP_#ITEMS_IBLOCK_ID#" => "-",
		"PROPERTY_CODE_#OFFERS_IBLOCK_ID#" => array(),
		"CART_PROPERTIES_#OFFERS_IBLOCK_ID#" => array(),
		"ADDITIONAL_PICT_PROP_#OFFERS_IBLOCK_ID#" => "",
		"OFFER_TREE_PROPS_#OFFERS_IBLOCK_ID#" => array("-")
	),
	false
);?>